
#people:
#  lastName: Javion
#  age: 18
#  boss: false
#  localDate: null
#  maps: {k1: v1,k2: v2}
#  objectList:
#    - lisi
#    - wangwu
#  dog:
#    name: petty
#    age: 2

#
#friends: {lastName: "zhangsan",age: 18}
#tomodaqi:
#  lastName: "lisi"
#  age: 20
#
#pets:
#  - "dong"
#  - "cat"
#  - "pig"
#animals: ["cat","dong","pig"]



server:
  port: 8080
spring:
  profiles:
    active:dev
---
server:
  port: 8081
spring:
  profiles: dev
---
server:
  port: 8082
spring:
  profiles: prod










